### ISSUE TITLE
The edit of the .env file removes the application key

### ISSUE THREAD

**Issue by megawubs** [sixlive/dotenv-editor#3]
## What are the steps to reproduce this issue?

1. Write any value to an .env file

## What happens?
`APP_KEY=base64...` gets reset to just `APP_KEY`

## What were you expecting to happen?
Keep the value of `APP_KEY`

## Any logs, error output, etc?
No

## Any other comments?
No

## What versions are you using?
**Operating System:** OSX Mojave
**Package Version:** `v1.1.0`

**Comment by sixlive** [comment]
Looking into this now

**Comment by megawubs** [comment]
To make it even a weirder bug: it seems to happen sometimes...

**Comment by sixlive** [comment]
This is because the `APP_KEY` ends in an `=`. I've changed this to work with regex for better control of how the key/value is split.

**Comment by megawubs** [comment]
🎊 👏 for the quick fix!
